#include <iostream>
#include <string>
#include <cstring>

using namespace std;

int main(){


    string fullName {};
    char fullNameediting[50] {};
    
    string firstName {};
    char firstNameediting[20] {};
    
    string secondName {};
    char secondNameediting[20] {};
    
    string thirdName {};
    char thirdNameediting[20] {};


    cout << "Enter your first name: ";
    cin.getline(firstNameediting,20);
    cout << firstNameediting[0];
    cout  << endl;

    


    cout << "----------------------------------------------------------------------- " << endl;
    cout << "                             Challeng                              " << endl;
    cout << "----------------------------------------------------------------------- " << endl;

    
    
    cout << "----------------------------------------------------------------------- " << endl;
    cout << "----------------------------------------------------------------------- " << endl;





}