#include <iostream>
#include <string>

using namespace std;


int main(){

    string element_one {};

    cout << "Enter a message: "<< endl;
    getline(cin, element_one);

    
    cout << "----------------------------------------------------------------------- " << endl;
    cout << "                             GetLine                              " << endl;
    cout << "----------------------------------------------------------------------- " << endl;

   
    cout << "Inserted message was: " << element_one << endl;


    cout << "----------------------------------------------------------------------- " << endl;
    cout << "----------------------------------------------------------------------- " << endl;






}