#include <iostream>

using namespace std;

int main(){

    /*Floating point types*/

    /*7 decimal digits*/
    float car_pyment {401.23};
    cout << "My car payment is " << car_pyment << endl;

    /*No less than float/ 15 decimal digits*/
    double pi {3.14159};
    cout << "Pi is: " << pi << endl;

    /*No less than double / 19 decimal digits */
    long double large_amount {2.7e120};
    cout << large_amount << " Is very big number" << endl;







}