#include <iostream>

using namespace std;

int main(){

    int nuumberOne, numberTwo;

    cout << boolalpha;
    cout << "Enter 2 interger separeted by a space:";
    cin >> nuumberOne >> numberTwo;

    cout << nuumberOne << " > " << numberTwo <<" : " << (nuumberOne > numberTwo) << endl;
    cout << nuumberOne << " < " << numberTwo <<" : " << (nuumberOne < numberTwo) << endl;
    cout << nuumberOne << " >= " << numberTwo <<" : " << (nuumberOne >= numberTwo) << endl;
    cout << nuumberOne << " <= " << numberTwo <<" : " << (nuumberOne <= numberTwo) << endl;
    cout << nuumberOne << " == " << numberTwo <<" : " << (nuumberOne == numberTwo) << endl;





}