#include <iostream>
#include <vector>

using namespace std;

int main(){


    //Declaring 
    /*
    This is the way to declaring vector in c++
    */
    vector <char> vowels (5);
    vector <int> test_score (10);

    //Initializng
    /* 
    Those are some ways to declaring vectors in c++
    */

    vector <char> vowels {'a','e','i','o','u'};
    
    vector <int> test_score {100,98,89,85,93};
    
    vector <double> hi_temperatures  (365,80.0);


    
    




}